# Creating Arrays

In [ ]:
import numpy as np
#creating 1d array
n1 = np.array([3,4,5,6])
print(n1)

[3 4 5 6]


In [ ]:
#creating 2d array
n2 = np.array([[3,5,6,7],[4,5,6,7]])
print(n2)

[[3 5 6 7]
 [4 5 6 7]]


In [ ]:
#zero filled 2d array
n3 = np.zeros([3,5],dtype='int32')
print(n3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
#array filled with ones
n4 = np.ones([2,3,3],dtype='int32')
print(n4)

[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
#empty array - contain random junk values
n5 = np.empty([1,3])
print(n5)

[[1.27702224e+232 4.95270032e+223 1.24805535e+243]]


In [ ]:
#create array with range of values
n6 = np.arange(10)
print(n6)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
n7 = np.arange(-5,30,5) #start,stop,step
print(n7)

[-5  0  5 10 15 20 25]


In [ ]:
#linearly spaced entries
n8 = np.linspace(0,20,num=8)
print(n8)

[ 0.          2.85714286  5.71428571  8.57142857 11.42857143 14.28571429
 17.14285714 20.        ]


In [ ]:
n9 = np.full([2,5],99) #create by specifying dimension and fill with values
print(n9)

[[99 99 99 99 99]
 [99 99 99 99 99]]


In [ ]:
n5.fill(9) #fill an array with values
print(n5)

[[9. 9. 9.]]


# Accessing

In [ ]:
print(n1[0])

3


In [ ]:
print(n1[-1])

6


In [ ]:
print(n2[1,0])

4


In [ ]:
print(n2[1,:])

[4 5 6 7]


In [ ]:
print(n2[:,3])

[7 7]


In [ ]:
n4[1,1,2] = 10
print(n4)

[[[ 1  1  1]
  [ 1  1  1]
  [ 1  1  1]]

 [[ 1  1  1]
  [ 1  1 10]
  [ 1  1  1]]]


# Size and Shape

In [ ]:
print(n4.ndim) #ndim gives number of dimensions or axes

3


In [ ]:
print(n4.shape)

(2, 3, 3)


In [ ]:
print(n4.size)

18


In [ ]:
print(n4.dtype)

int32


In [ ]:
print(n4.itemsize)

4


In [ ]:
print(n4.nbytes)

72


# Sorting

In [ ]:
n10 = np.array([3,4,1,9,5,10,8,7])
np.sort(n10)

array([ 1,  3,  4,  5,  7,  8,  9, 10])

In [ ]:
n11 = np.array([[6, 2, 7], [5, 10, 1]])
np.sort(n11) #default is axis=-1 which is the last axis

array([[ 2,  6,  7],
       [ 1,  5, 10]])

In [ ]:
np.sort(n11,axis=0)

array([[ 5,  2,  1],
       [ 6, 10,  7]])

In [ ]:
np.sort(n11,axis=1)

array([[ 2,  6,  7],
       [ 1,  5, 10]])

# Reshaping and Array Conversions

In [ ]:
n12 = n10.reshape(2,4)
print(n12)

[[ 3  4  1  9]
 [ 5 10  8  7]]


In [ ]:
#Joining 2 arrays using concatenate
n13 = np.arange(4)
print(n13)
n14 = np.arange(5,9)
print(n14)
n15 = np.concatenate((n13,n14))
print(n15)

[0 1 2 3]
[5 6 7 8]
[0 1 2 3 5 6 7 8]


In [ ]:
#converting 1d array to 2d array
n16 = np.arange(8)
print(n16)
n17 = n16[np.newaxis,:]
print(n17)
print(n17.shape)
n18 = n16[:,np.newaxis]
print(n18)
print(n18.shape)

[0 1 2 3 4 5 6 7]
[[0 1 2 3 4 5 6 7]]
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [ ]:
n19 = np.expand_dims(n16,axis = 1)
print(n19)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [ ]:
n20 = np.expand_dims(n16,axis = 0)
print(n20)

[[0 1 2 3 4 5 6 7]]


# Indexing and slicing

In [ ]:
n21 = np.arange(10)
print(n21)
print(n21[n21<5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [ ]:
print(n21[(n21>3) & (n21<8)])

[4 5 6 7]


In [ ]:
five_up = n21>5
print(five_up)
print(n21[five_up])

[False False False False False False  True  True  True  True]
[6 7 8 9]


In [ ]:
n21[6] = 100
print(np.nonzero(n21>5))

(array([6, 7, 8, 9], dtype=int64),)


In [ ]:
print(n21[3:7])

[  3   4   5 100]


# Stack, Split

In [ ]:
n22 = np.array([[1,2],[3,4]])
n23 = np.array([[5,6],[7,8]])
np.hstack((n22,n23))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
np.vstack((n22,n23))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
n24 = np.arange(20)
print(n24)
np.hsplit(n24,4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19])]

# Copy

In [ ]:
n25 = n24[0:5] # shallow copy
n24[0] = 100
print(n24)
print(n25)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100   1   2   3   4]


In [ ]:
#deep copy
n26 = n24.copy()
n24[1]= 200
print(n24)
print(n26)

[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


# Math

In [ ]:
print(n22)
print(n23)
print(n22+n23)
print(n23*n23)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[25 36]
 [49 64]]


In [ ]:
print(n26)
print(n26.sum())
print(n26.max())
print(n26.min())
print(n26*10)

[100 200   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
489
200
2
[1000 2000   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190]


In [ ]:
print(np.cos(n26))

[ 0.86231887  0.48718768 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396  0.90744678  0.13673722 -0.75968791 -0.95765948 -0.27516334
  0.66031671  0.98870462]


# Random Numbers

In [ ]:
np.random.rand(3,3)

array([[0.6756754 , 0.58657492, 0.42845491],
       [0.48703211, 0.25432168, 0.89789337],
       [0.65050801, 0.58615413, 0.57901873]])

In [ ]:
np.random.randint(100,size=(4,2))

array([[65, 82],
       [89, 38],
       [39, 56],
       [98, 76]])